version: '2'
services:
    eknow-app:
        image: eknow
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://eknow-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=eknow
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eknow-mongodb:
        extends:
            file: mongodb.yml
            service: eknow-mongodb
